name: Deploy Chrome Extension

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Package Extension
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload & Publish Extension
        uses: browser-actions/release-chrome-extension@v3
        with:
          extension-id: ${{ secrets.CHROME_EXTENSION_ID }}
          extension-path: ./chrome-extension.zip
          oauth-client-id: ${{ secrets.CHROME_CLIENT_ID }}
          oauth-client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          oauth-refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}